### ISSUE TITLE
Not all libraries are requested by CMakeLists.txt

### ISSUE THREAD

**Issue by ooxi** [ZahlGraf/IrrlichtCMake#2]
The following libraries are tried to link by make but not required by CMake

```
/usr/bin/ld: cannot find -lXft
/usr/bin/ld: cannot find -lfontconfig
```

**Comment by ZahlGraf** [comment]
They are added to the library list in this file:
https://github.com/ZahlGraf/IrrlichtCMake/blob/master/CMake/OperatingSystems/UnixLikeSettings.cmake

Since it is only a requirement of Unix. On windows you cannot link against them. 
Have you any issues here?

**Comment by ooxi** [comment]
Yes the issue is that cmake generates make files even if `libXft` and `libfontconfig` are not found on the system. Maybe we should use something like [FindFontconfig.cmake](https://github.com/WebKit/webkit/blob/master/Source/cmake/FindFontconfig.cmake) to ensure fontconfig is installed and found :)

**Comment by ZahlGraf** [comment]
Ok now I understand what you mean, however Fontconfig und Xft is a requirement for Irrlicht so far as I know. Of course we can use FindFontconfig anyway to fail earlier, when this is not installed at the computer.

**Comment by ooxi** [comment]
This would be great! I couldn't find time to prepare a patch but I'm happy to test one :)

**Comment by ZahlGraf** [comment]
Today I released the 0.2.2 version, with your bugfix and with a change related to this issue:
Now X11, Xft, Freetype and Fontconfig are searched by findlib functionality of CMake.
I also noticed, that Xft, Freetype and Fontconfig is not a requirement of Irrlicht as library, but a requirement of some Tools and Examples.
Thus, when the user does not want to compile tools and examples, it will not link against such libraries... so you can compile the Irrlicht library also without having those libraries installed.
When the user want to compile the tools and examples, but does not have those libraries installed, CMake will print a warning, that not all tools/examples may compile.

Maybe you can check at your Linux system, if this works for you?

**Comment by ZahlGraf** [comment]
This issue is related to the following commits:
233cf1f26b29229c95426987628fd6eec6736f24
8aa76eae8c746cbe3d86bf723974650158e55c3b
69f35ff0f4be1884748499b857805d180a5c4ecc
84d461ef7933b5f8a50e39be60ccb2135272e1ef
d5363eabaed5fa33213772f1a305c459cdd42e3f

**Comment by ooxi** [comment]
That's great! I'll try the new version as soon as possible and report back :)
