### ISSUE TITLE
MingW64 and Windows 7 install incorrectly.

### ISSUE THREAD

**Issue by WatIsDeze** [ZahlGraf/IrrlichtCMake#3]
I figured I'd post this as an issue, despite being new to using MingW64 and Windows 7. (Usually work on a Linux box.)

Today I tried to build Irrlicht using this project, it works like a charm unlike its original make file.

The problem seems to be that when I do make install, it install into C:\Program Files(x86)\Irrlicht\....
Now if I am not mistaking, in the case of MingW64 it should install into the MingW folders.

![image](https://user-images.githubusercontent.com/10252874/55618268-63a55000-5796-11e9-86b3-8384a3b1d1d2.png)

Sadly I am not too experienced with CMake on Windows and have no clue how to fix it, so I am dropping this as an issue instead of a patch.

**Comment by ZahlGraf** [comment]
@WatIsDeze 

You can very easy influence the directory where to store Irrlicht by changing the CMake Variable ```CMAKE_INSTALL_PREFIX```. 
If you don't know how to change it, simply follow the instructions from [here](https://github.com/ZahlGraf/IrrlichtCMake#-compiling-the-whole-library).

I hope this solves your issue. If not, simply re-open it again.

BTW: I did not adapted the CMake files to a new version of irrlicht. I even have no access to the build environment at the moment. So if you use the build system with a more recent version than 1.8.3 of irrlicht, there could be some issues. However pull-requests for adapting to new versions are very welcome.

Best regards!
